### ISSUE TITLE
Vis Clip Crashes Client/Server

### ISSUE THREAD

**Issue by SteelyJohnson** [TGiFallen/Clip_Tool#4] opened 2015-07-25 22:44 UTC
Using Advanced Duplicator 2, saving a previously made object that contains visclip as a new save, and then spawning it, it will crash the server/client. This is also reproducable. Here is a crash log download: http://www.mediafire.com/download/zhw0y469ip7dwuf/hl2_150628_crash_2015_7_25T22_19_45C0.mdmp

**Comment by looterz** [comment] 2015-07-28 00:51
If I remember correctly, this is caused by the advanced dupe contraption having many visclips associated with it, and due to how the clips are sent to the client it can overload the client and cause a crash.

The guilty code is located here https://github.com/TGiFallen/Clip_Tool/blob/master/lua/autorun/server/sv_clipping.lua#L68

I don't have garrysmod installed or setup for building right now or id submit a patch, but I'm leaving this info here hoping TGiFallen will find it. I'd recommend throttling or splitting up the way clips are sent to clients to avoid crashing them.

**Comment by TGiFallen** [comment] 2015-08-05 17:56
I'd love to get to fix it, though I'm unsure if I have the time, I am due to head out to baffin island soon and there's no internet where I'm going. I'll take a look.

**Comment by FreeeFry** [comment] 2015-08-08 01:53
>  looterz:
>If I remember correctly, this is caused by the advanced dupe contraption having many visclips associated with it, and due to how the clips are sent to the client it can overload the client and cause a crash.

>The guilty code is located here https://github.com/TGiFallen/Clip_Tool/blob/master/lua/autorun/server/sv_clipping.lua#L68

> I don't have garrysmod installed or setup for building right now or id submit a patch, but I'm leaving this info here hoping TGiFallen will find it. I'd recommend throttling or splitting up the way clips are sent to clients to avoid crashing them.


This is actually not the case(assuming this is the same issue I've had with a few dupes of mine).
After some debugging it turns out it has to do with the compatibility code for older visclip versions;
Sometimes the EntityMods table of an entity might contain both the **clipping_all_prop_clips** table(newer system) AND the **clips** table(older system), this seems to crash the server when duplicator.StoreEntityModifier is called in sv_clipping.lua on line 58.

I've implemented a fix for this by adding  this to compat.lua on line 5:
```
if ent:GetTable().EntityMods and ent:GetTable().EntityMods.clipping_all_prop_clips then return end
```

And to make sure the old clips table is removed from future saves I've also added this to sv_clipping.lua at line 56:
```
if ent:GetTable().EntityMods and ent:GetTable().EntityMods.clips then ent:GetTable().EntityMods.clips = nil end 
```

To verify this is the case comment out/remove line 58 in sv_clipping.lua and spawn your crashing dupe, then while looking at an entity which that's clipped enter this into your console:
```
lua_run PrintTable(player.GetAll()[1]:GetEyeTrace().Entity:GetTable())
```
You should see that it has both the **clipping_all_prop_clips** and the **clips** sub-tables of the **EntityMods** table.

**Closed** 2015-08-08 17:31 UTC
